description = "Web Servlet Library unit tests"
tags = ["web", "servlet", "http", "json"]
name = "servletada_tests"
version = "1.8.1"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["servletada_tests.gpr"]
website = "https://gitlab.com/stcarrez/ada-servlet"

[[depends-on]]
servletada = "*"
servletada_unit = "*"
servletada_aws = "*"
servletada_ews = "*"
utilada_aws = "^2.8.0"
utilada_unit = "^2.8.2"

[configuration]
disabled = true

[[pins]]
servletada = { path = '..' }
servletada_unit = { path = '../unit' }
servletada_aws = { path = '../aws' }
servletada_ews = { path = '../ews' }
